// <auto-generated />
using System;
using CarAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240605094400_AddKøreseddelPrimaryKey")]
    partial class AddKøreseddelPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCalendar.Models.KoreseddelModel", b =>
                {
                    b.Property<int>("KoreseddelModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoreseddelModelId"));

                    b.Property<string>("BilId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bruger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraDestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KmSlut")
                        .HasColumnType("int");

                    b.Property<int>("KmStart")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutDato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("TilDestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KoreseddelModelId");

                    b.ToTable("Køresedler");
                });
#pragma warning restore 612, 618
        }
    }
}
